/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tienda.ui;

import com.tienda.dao.GenericDAO;
import com.tienda.entities.Productos;
import com.tienda.entities.Usuarios;
import com.tienda.entities.Ventas;
import com.tienda.util.Util;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MBN USER
 */
public class Registro_ventas extends javax.swing.JInternalFrame {

    private GenericDAO dao;
    private Usuarios usuario;
    public DefaultTableModel model;
    String CODIGO = "";
    double SUBTOTAL = 0.0;
    double IVA = 0.0;
    double TOTAL = 0.0;
    int NUM_PRODUCTOS = 1;

    /**
     * Creates new form Registro_ventas
     */
    public Registro_ventas(GenericDAO dao, Usuarios usuario) {
        initComponents();

        //Se recibe el dao y usuario desde el jframe inicio
        this.dao = dao;
        this.usuario = usuario;

        //Se establecen los titulos de la tabla
        String titulos[] = {"Código", "Num. productos", "Producto", "Descripción", "Precio Unitario"};
        model = new DefaultTableModel(null, titulos);
        tablaProductos.setModel(model);

        //Se establece el IVA, total y Num de productos inicial
        lblSubtotal.setText(SUBTOTAL + "");
        lblIva.setText(IVA + "");
        lblTotal.setText(TOTAL + "");
        txtNumProductos.setText(NUM_PRODUCTOS + "");

        //Se establece la fecha
        lblFecha.setText("Fecha: " + Util.formatearFecha(new Date()));
    }

    public void limpiarFormulario() {
        //Remueve los elementos contenidos en la tabla
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        SUBTOTAL = 0.0;
        IVA = 0.0;
        TOTAL = 0.0;

        lblSubtotal.setText(SUBTOTAL + "");
        lblIva.setText(IVA + "");
        lblTotal.setText(TOTAL + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumProductos = new javax.swing.JTextField();
        btnSumarNumProductos = new javax.swing.JButton();
        restarNumProductos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnVender = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Registro de ventas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Código:");

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFecha.setText("Fecha:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tienda/iconos/multiply.png"))); // NOI18N

        txtNumProductos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnSumarNumProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tienda/iconos/plus.png"))); // NOI18N
        btnSumarNumProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarNumProductosActionPerformed(evt);
            }
        });

        restarNumProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tienda/iconos/minus.png"))); // NOI18N
        restarNumProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarNumProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSumarNumProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restarNumProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigo)
                        .addComponent(jLabel4))
                    .addComponent(btnSumarNumProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(restarNumProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(txtNumProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFecha))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("TOTAL: $");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTotal.setText("-");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        jScrollPane2.setViewportView(jScrollPane1);

        btnVender.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tienda/iconos/shoping-cart.png"))); // NOI18N
        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("IVA: $");

        lblIva.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblIva.setText("-");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Subtotal: $");

        lblSubtotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSubtotal.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal)
                            .addComponent(lblIva)
                            .addComponent(lblSubtotal))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblSubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblIva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVender)
                    .addComponent(lblTotal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        CODIGO = txtCodigo.getText().trim();

        //Se consulta el producto
        Productos producto = dao.buscarProductoPorCodigo(CODIGO);
        if (producto != null) {
            /*
            for (int row = 0; row < model.getRowCount(); row++) {
                String CODIGO_REGISTRADO = model.getValueAt(row, 0).toString();
                if(){
                    
                }
            }
             */

            Object[] row = new Object[5];
            row[0] = producto.getProductoId();
            row[1] = NUM_PRODUCTOS;
            row[2] = producto.getNombre();
            row[3] = producto.getTamano();
            row[4] = producto.getPrecio();
            model.addRow(row);
            tablaProductos.setModel(model);

            //Se calcula el Subtotal, IVA y el precio final
            SUBTOTAL += producto.getPrecio();
            IVA = SUBTOTAL * 0.16;
            TOTAL = SUBTOTAL + IVA;

            //Se establecen los datos en la vista
            lblSubtotal.setText(SUBTOTAL + "");
            lblTotal.setText(TOTAL + "");
            lblIva.setText(IVA + "");
        } else {
            JOptionPane.showMessageDialog(this, "Producto no encontrado", "Error!", JOptionPane.ERROR_MESSAGE);
        }

        //Se limpia el campo de codigo de barras
        txtCodigo.setText("");
        //Se reestablece el numero de productos por default
        txtNumProductos.setText(1 + "");
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnSumarNumProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarNumProductosActionPerformed
        NUM_PRODUCTOS++;
        txtNumProductos.setText(NUM_PRODUCTOS + "");
    }//GEN-LAST:event_btnSumarNumProductosActionPerformed

    private void restarNumProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restarNumProductosActionPerformed
        if (NUM_PRODUCTOS != 0) {
            NUM_PRODUCTOS--;
            txtNumProductos.setText(NUM_PRODUCTOS + "");
        }
    }//GEN-LAST:event_restarNumProductosActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        boolean ventaGuardada = true;

        for (int i = 0; i < model.getRowCount(); i++) {
            String productoId = model.getValueAt(i, 0).toString();
            double precioUnitario = Double.parseDouble(model.getValueAt(i, 4).toString());
            int numProductos = Integer.parseInt(model.getValueAt(i, 1).toString());
            double subtotal = numProductos * precioUnitario;
            double iva = subtotal * 0.16;
            double total = subtotal + iva;

            Productos producto = new Productos();
            producto.setProductoId(productoId);

            Ventas venta = new Ventas();
            venta.setMonto(total);
            venta.setFecha(new Date());
            venta.setProductos(producto);
            venta.setUsuarios(usuario);

            //Se guarda la venta
            if (dao.guardar(venta)) {
                //Se disminuye la existencia del producto
                dao.actualizarExistenciaProducto(productoId, numProductos);
                
//                //Se envia el mensaje si la existencia es menor o igual a la cantidad minima
//                Productos productoEvaluado = dao.buscarProductoPorCodigo(productoId);
//                if (productoEvaluado.getExistencia() <= productoEvaluado.getExistenciaMin()) {
//                    System.out.println("ESCASES DE PRODUCTO ===========>>");
//                    System.out.println("Proveedor: "+productoEvaluado.getProveedores().getNombre());
//                    System.out.println("Telefono: "+productoEvaluado.getProveedores().getNombre());
//                }
            } else {
                ventaGuardada = false;
                break;
            }
        }

        if (ventaGuardada) {
            JOptionPane.showMessageDialog(this, "Venta registrada satisfactoriamente", "Éxito!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar la venta", "Error!", JOptionPane.ERROR_MESSAGE);
        }

        //Se limpian los datos del formulario
        limpiarFormulario();
    }//GEN-LAST:event_btnVenderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSumarNumProductos;
    private javax.swing.JButton btnVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JButton restarNumProductos;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNumProductos;
    // End of variables declaration//GEN-END:variables
}
