package com.tienda.entities;
// Generated 20/08/2017 06:27:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriasProductos generated by hbm2java
 */
public class CategoriasProductos  implements java.io.Serializable {


     private int categoriaProductoId;
     private String nombre;
     private Set productoses = new HashSet(0);

    public CategoriasProductos() {
    }

	
    public CategoriasProductos(int categoriaProductoId, String nombre) {
        this.categoriaProductoId = categoriaProductoId;
        this.nombre = nombre;
    }
    public CategoriasProductos(int categoriaProductoId, String nombre, Set productoses) {
       this.categoriaProductoId = categoriaProductoId;
       this.nombre = nombre;
       this.productoses = productoses;
    }
   
    public int getCategoriaProductoId() {
        return this.categoriaProductoId;
    }
    
    public void setCategoriaProductoId(int categoriaProductoId) {
        this.categoriaProductoId = categoriaProductoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


