package com.tienda.entities;
// Generated 20/08/2017 06:27:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private String productoId;
     private CategoriasProductos categoriasProductos;
     private Proveedores proveedores;
     private String nombre;
     private String tamano;
     private double precio;
     private int existencia;
     private int existenciaMin;
     private int cantidadSolicitada;
     private Set ventases = new HashSet(0);

    public Productos() {
    }

	
    public Productos(String productoId, CategoriasProductos categoriasProductos, Proveedores proveedores, String nombre, String tamano, double precio, int existencia, int existenciaMin, int cantidadSolicitada) {
        this.productoId = productoId;
        this.categoriasProductos = categoriasProductos;
        this.proveedores = proveedores;
        this.nombre = nombre;
        this.tamano = tamano;
        this.precio = precio;
        this.existencia = existencia;
        this.existenciaMin = existenciaMin;
        this.cantidadSolicitada = cantidadSolicitada;
    }
    public Productos(String productoId, CategoriasProductos categoriasProductos, Proveedores proveedores, String nombre, String tamano, double precio, int existencia, int existenciaMin, int cantidadSolicitada, Set ventases) {
       this.productoId = productoId;
       this.categoriasProductos = categoriasProductos;
       this.proveedores = proveedores;
       this.nombre = nombre;
       this.tamano = tamano;
       this.precio = precio;
       this.existencia = existencia;
       this.existenciaMin = existenciaMin;
       this.cantidadSolicitada = cantidadSolicitada;
       this.ventases = ventases;
    }
   
    public String getProductoId() {
        return this.productoId;
    }
    
    public void setProductoId(String productoId) {
        this.productoId = productoId;
    }
    public CategoriasProductos getCategoriasProductos() {
        return this.categoriasProductos;
    }
    
    public void setCategoriasProductos(CategoriasProductos categoriasProductos) {
        this.categoriasProductos = categoriasProductos;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTamano() {
        return this.tamano;
    }
    
    public void setTamano(String tamano) {
        this.tamano = tamano;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public int getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(int existencia) {
        this.existencia = existencia;
    }
    public int getExistenciaMin() {
        return this.existenciaMin;
    }
    
    public void setExistenciaMin(int existenciaMin) {
        this.existenciaMin = existenciaMin;
    }
    public int getCantidadSolicitada() {
        return this.cantidadSolicitada;
    }
    
    public void setCantidadSolicitada(int cantidadSolicitada) {
        this.cantidadSolicitada = cantidadSolicitada;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }




}


