package com.tienda.entities;
// Generated 19/08/2017 08:06:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TiposUsuarios generated by hbm2java
 */
public class TiposUsuarios  implements java.io.Serializable {


     private int tipoUsuarioId;
     private String nombre;
     private Set usuarioses = new HashSet(0);

    public TiposUsuarios() {
    }

	
    public TiposUsuarios(int tipoUsuarioId, String nombre) {
        this.tipoUsuarioId = tipoUsuarioId;
        this.nombre = nombre;
    }
    public TiposUsuarios(int tipoUsuarioId, String nombre, Set usuarioses) {
       this.tipoUsuarioId = tipoUsuarioId;
       this.nombre = nombre;
       this.usuarioses = usuarioses;
    }
   
    public int getTipoUsuarioId() {
        return this.tipoUsuarioId;
    }
    
    public void setTipoUsuarioId(int tipoUsuarioId) {
        this.tipoUsuarioId = tipoUsuarioId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


