package com.tienda.entities;
// Generated 6/08/2017 10:25:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private int ventaId;
     private Productos productos;
     private Usuarios usuarios;
     private int monto;
     private Date fecha;

    public Ventas() {
    }

    public Ventas(int ventaId, Productos productos, Usuarios usuarios, int monto, Date fecha) {
       this.ventaId = ventaId;
       this.productos = productos;
       this.usuarios = usuarios;
       this.monto = monto;
       this.fecha = fecha;
    }
   
    public int getVentaId() {
        return this.ventaId;
    }
    
    public void setVentaId(int ventaId) {
        this.ventaId = ventaId;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


